org.gradle.jvmargs=-Xmx2G

# Fabric Properties
    minecraft_version = 1.20.1
    loader_version = 0.16.14

# Mod Properties
    mod_version = 0.2.0
    maven_group = github.totorewa.tcpshield
    archives_base_name = tcpshield-fabric

# Dependencies
    fabric_api_version = 0.92.2+1.20.1
    snakeyaml_version = 2.2
